### ISSUE TITLE
Accumulation of evidence

### ISSUE THREAD

**Issue by yallup** [handley-lab/blackjax#8]
Issue still persists with evidence accumulation over parralel chains, see below, for small numbers of parallel chains (n_delete) it seems ~acceptable, but grows for larger numbers of chains. I will leave this for now and make the PR as it’s acceptably working, but one to fix before full merging.

n_delete 20
Analytic evidence: -57.51
Estimated evidence: -57.40 +- 0.28
Internal Evidence estimate: -56.69

n_delete 100
Analytic evidence: -57.51
Estimated evidence: -57.56 +- 0.31
Internal Evidence estimate: -53.64

**Comment by williamjameshandley** [comment]
I think that after the fixes from 652fb05abc63defc746e55e1b26d4add812cf0b8 and 652fb05abc63defc746e55e1b26d4add812cf0b8, what we wrote last week is now correct, so have reinstated this in 685e7818069dda32f67d2ae176af2a32a3d45d41.
